######################################################################
# Automatically generated by qmake (3.0) ?? 5? 27 14:43:17 2015
######################################################################
QT  +=  widgets
TEMPLATE = app
TARGET = jesenScene
INCLUDEPATH += . untitled

# Input
HEADERS += DButton.h DComponent.h DSwitchbutton.h 
SOURCES += DButton.cpp \
           DComponent.cpp \
           DSwitchbutton.cpp \
           main.cpp \
